# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# prepare:
#   mkdir -p /var/disk1/containers/bunker006/data/{ngxconf,bwdata}
#   chmod 770 /var/disk1/containers/bunker006/data/*
#   sudo chgrp 100100 /var/disk1/containers/bunker006/data/*
# 
# Created with podman-4.3.1
#
# NOTE: If you generated this yaml from an unprivileged and rootless podman container on an SELinux
# enabled system, check the podman generate kube man page for steps to follow to ensure that your pod/container
# has the right permissions to access the volumes added.
---
apiVersion: v1
kind: Pod
metadata:
  annotations:
    io.kubernetes.cri-o.TTY/bunkerweb: "false"
    io.podman.annotations.autoremove/bunkerweb: "FALSE"
    io.podman.annotations.init/bunkerweb: "FALSE"
    io.podman.annotations.privileged/bunkerweb: "FALSE"
    io.podman.annotations.publish-all/bunkerweb: "FALSE"
  creationTimestamp: "2023-01-03T15:23:53Z"
  labels:
    app: bunkerweb
  name: bunkerweb
spec:
  automountServiceAccountToken: false
  restartPolicy: Never
  # KEEP "hostNetwork: true" to avoid podman internal IP address mapping !!
  hostNetwork: true
  hostname: bunkerweb
  containers:
  - name: app
    image: docker.io/bunkerity/bunkerweb:1.4.8
    env:
    - name: DNS_RESOLVERS
      value: 8.8.8.8 8.8.4.4
    - name: API_WHITELIST_IP
      value: 127.0.0.0/8 10.20.30.0/24
    - name: LOG_LEVEL
      value: info
    - name: MULTISITE
      value: "yes"
    - name: SERVER_NAME
      value: bwadm.citizens4digital.com cossen.citizens4digital.com oberhain.citizens4digital.com pve29.citizens4digital.com pve30.citizens4digital.com sorry.citizens4digital.com www.citizens4digital.com clock.citizens4digital.com gics.citizens4digital.com iam.citizens4digital.com demo.citizens4digital.com
    - name: www.citizens4digital.com_SERVER_NAME
      value: www.citizens4digital.com
    - name: www.citizens4digital.com_AUTO_LETS_ENCRYPT
      value: "yes"
    - name: www.citizens4digital.com_EMAIL_LETS_ENCRYPT
      value: privacy@citizens4digital.com
    - name: www.citizens4digital.com_USE_LETS_ENCRYPT_STAGING
      value: "yes"
    - name: sorry.citizens4digital.com_SERVER_NAME
      value: sorry.citizens4digital.com
    - name: sorry.citizens4digital.com_AUTO_LETS_ENCRYPT
      value: "yes"
    - name: sorry.citizens4digital.com_EMAIL_LETS_ENCRYPT
      value: privacy@citizens4digital.com
    - name: sorry.citizens4digital.com_USE_LETS_ENCRYPT_STAGING
      value: "yes"
    - name: sorry.citizens4digital.com_USE_CORS
      value: "yes"
    # - name: sorry.citizens4digital.com_CONTENT_SECURITY_POLICY
    #   value: "object-src 'none'; frame-ancestors 'self';"
    - name: cossen.citizens4digital.com_SERVER_NAME
      value: cossen.citizens4digital.com
    - name: cossen.citizens4digital.com_AUTO_LETS_ENCRYPT
      value: "yes"
    - name: cossen.citizens4digital.com_EMAIL_LETS_ENCRYPT
      value: privacy@citizens4digital.com
    - name: cossen.citizens4digital.com_USE_LETS_ENCRYPT_STAGING
      value: "yes"
    - name: oberhain.citizens4digital.com_SERVER_NAME
      value: oberhain.citizens4digital.com
    - name: oberhain.citizens4digital.com_AUTO_LETS_ENCRYPT
      value: "yes"
    - name: oberhain.citizens4digital.com_EMAIL_LETS_ENCRYPT
      value: privacy@citizens4digital.com
    - name: oberhain.citizens4digital.com_USE_LETS_ENCRYPT_STAGING
      value: "yes"
    - name: pve29.citizens4digital.com_SERVER_NAME
      value: pve29.citizens4digital.com
    - name: pve29.citizens4digital.com_AUTO_LETS_ENCRYPT
      value: "yes"
    - name: pve29.citizens4digital.com_EMAIL_LETS_ENCRYPT
      value: privacy@citizens4digital.com
    - name: pve29.citizens4digital.com_USE_LETS_ENCRYPT_STAGING
      value: "yes"
    - name: pve29.citizens4digital.com_USE_REVERSE_PROXY
      value: "yes"
    - name: pve29.citizens4digital.com_REVERSE_PROXY_WS
      value: "yes"
    - name: pve29.citizens4digital.com_REVERSE_PROXY_URL
      value: /
    - name: pve29.citizens4digital.com_REVERSE_PROXY_HOST
      value: https://172.29.12.29:8006
    - name: pve29.citizens4digital.com_ALLOWED_METHODS
      value: GET|POST|PUT|HEAD
    - name: pve29.citizens4digital.com_LIMIT_REQ_RATE
      value: 70r/s
    - name: pve30.citizens4digital.com_SERVER_NAME
      value: pve30.citizens4digital.com
    - name: pve30.citizens4digital.com_AUTO_LETS_ENCRYPT
      value: "yes"
    - name: pve30.citizens4digital.com_EMAIL_LETS_ENCRYPT
      value: privacy@citizens4digital.com
    - name: pve30.citizens4digital.com_USE_LETS_ENCRYPT_STAGING
      value: "yes"
    - name: pve30.citizens4digital.com_USE_REVERSE_PROXY
      value: "yes"
    - name: pve30.citizens4digital.com_REVERSE_PROXY_WS
      value: "yes"
    - name: pve30.citizens4digital.com_REVERSE_PROXY_URL
      value: /
    - name: pve30.citizens4digital.com_REVERSE_PROXY_HOST
      value: https://172.29.12.30:8006
    - name: pve30.citizens4digital.com_ALLOWED_METHODS
      value: GET|POST|PUT|HEAD
    - name: pve30.citizens4digital.com_LIMIT_REQ_RATE
      value: 70r/s
    - name: demo.citizens4digital.com_SERVER_NAME
      value: demo.citizens4digital.com
    - name: demo.citizens4digital.com_AUTO_LETS_ENCRYPT
      value: "yes"
    - name: demo.citizens4digital.com_EMAIL_LETS_ENCRYPT
      value: privacy@citizens4digital.com
    - name: demo.citizens4digital.com_USE_LETS_ENCRYPT_STAGING
      value: "yes"
    - name: demo.citizens4digital.com_USE_REVERSE_PROXY
      value: "yes"
    - name: demo.citizens4digital.com_REVERSE_PROXY_URL
      value: /
    - name: demo.citizens4digital.com_REVERSE_PROXY_HOST
      value:  http://127.0.0.1:9000
    - name: demo.citizens4digital.com_USE_AUTH_BASIC
      value: "yes"
    - name: demo.citizens4digital.com_AUTH_BASIC_USER
      value: karlder
    - name: demo.citizens4digital.com_AUTH_BASIC_PASSWORD
      value: kaefer
    - name: clock.citizens4digital.com_SERVER_NAME
      value: clock.citizens4digital.com
    - name: clock.citizens4digital.com_AUTO_LETS_ENCRYPT
      value: "yes"
    - name: clock.citizens4digital.com_EMAIL_LETS_ENCRYPT
      value: privacy@citizens4digital.com
    - name: clock.citizens4digital.com_USE_LETS_ENCRYPT_STAGING
      value: "yes"
    - name: iam.citizens4digital.com_SERVER_NAME
      value: iam.citizens4digital.com
    - name: iam.citizens4digital.com_AUTO_LETS_ENCRYPT
      value: "yes"
    - name: iam.citizens4digital.com_EMAIL_LETS_ENCRYPT
      value: privacy@citizens4digital.com
    - name: iam.citizens4digital.com_USE_LETS_ENCRYPT_STAGING
      value: "yes"
    - name: iam.citizens4digital.com_LIMIT_REQ_RATE
      value: 90r/s
    - name: iam.citizens4digital.com_USE_REVERSE_PROXY
      value: "yes"
    - name: iam.citizens4digital.com_REVERSE_PROXY_URL
      value: /
    - name: iam.citizens4digital.com_REVERSE_PROXY_HOST
      value: http://127.0.0.1:8082 ## only if Hostnetwork==true else use eth0 IP addr
    - name: iam.citizens4digital.com_COOKIE_FLAGS
      value: " "
      # value: / HttpOnly SameSite
    - name: iam.citizens4digital.com_COOKIE_AUTO_SECURE_FLAG
      value: "yes"
    - name: iam.citizens4digital.com_REVERSE_PROXY_HEADERS
      value: "X-Forwarded-Proto: https"
    - name: iam.citizens4digital.com_USE_MODSECURITY
      value: "no"
    - name: iam.citizens4digital.com_USE_MODSECURITY_CRS
      value: "no"
    - name: iam.citizens4digital.com_ALLOWED_METHODS
      value: "GET|POST|PUT|HEAD"
    - name: iam.citizens4digital.com_REFERRER_POLICY
      value: "*"
    - name: iam.citizens4digital.com_PERMISSIONS_POLICY
      value: " "
    - name: iam.citizens4digital.com_CONTENT_SECURITY_POLICY
      value: "object-src 'none'; frame-ancestors 'self';"
    - name: iam.citizens4digital.com_FEATURE_POLICY
      value: " "
    - name: gics.citizens4digital.com_CONTENT_SECURITY_POLICY
      value: "object-src 'none'; frame-ancestors 'self';"
    - name: gics.citizens4digital.com_USE_MODSECURITY
      value: "no"
    - name: gics.citizens4digital.com_USE_MODSECURITY_CRS
      value: "no"
    - name: gics.citizens4digital.com_REVERSE_PROXY_HEADERS
      value: "X-Forwarded-Proto: https"
    - name: gics.citizens4digital.com_SERVER_NAME
      value: gics.citizens4digital.com
    - name: gics.citizens4digital.com_AUTO_LETS_ENCRYPT
      value: "yes"
    - name: gics.citizens4digital.com_EMAIL_LETS_ENCRYPT
      value: privacy@citizens4digital.com
    - name: gics.citizens4digital.com_USE_LETS_ENCRYPT_STAGING
      value: "yes"
    - name: gics.citizens4digital.com_USE_REVERSE_PROXY
      value: "yes"
    - name: gics.citizens4digital.com_COOKIE_FLAGS
      value: " "
    - name: gics.citizens4digital.com_REVERSE_PROXY_URL
      value: /
      # value: /gics-web/
    - name: gics.citizens4digital.com_REVERSE_PROXY_HOST
      value:  http://127.0.0.1:8085
      # value:  http://172.29.12.158:8085/gics-web/
    - name: gics.citizens4digital.com_REVERSE_PROXY_INTERCEPT_ERRORS
      value: "no"
    - name: gics.citizens4digital.com_LIMIT_REQ_RATE
      value: 70r/s
#    - name: gics.citizens4digital.com_REVERSE_PROXY_HEADERS
#      value: "X-Script-Name /gics-web"
    - name: bwadm.citizens4digital.com_SERVER_NAME
      value: bwadm.citizens4digital.com
    - name: bwadm.citizens4digital.com_AUTO_LETS_ENCRYPT
      value: "yes"
    - name: bwadm.citizens4digital.com_EMAIL_LETS_ENCRYPT
      value: privacy@citizens4digital.com
    - name: bwadm.citizens4digital.com_USE_LETS_ENCRYPT_STAGING
      value: "yes"
    # ports:
    # - containerPort: 8080
    #   hostPort: 8080
    # - containerPort: 8443
    #   hostPort: 8443
    securityContext:
      capabilities:
        drop:
        - CAP_MKNOD
        - CAP_NET_RAW
        - CAP_AUDIT_WRITE
    volumeMounts:
    - mountPath: /data
      name: var-disk1-containers-bunker006-data-bwdata-host-0
    - mountPath: /etc/nginx
      name: var-disk1-containers-bunker006-data-ngxconf-host-1
  enableServiceLinks: false
  volumes:
  - hostPath:
      path: /var/disk1/containers/bunker006/data/bwdata
      type: DirectoryOrCreate
    name: var-disk1-containers-bunker006-data-bwdata-host-0
  - hostPath:
      path: /var/disk1/containers/bunker006/data/ngxconf
      type: DirectoryOrCreate
    name: var-disk1-containers-bunker006-data-ngxconf-host-1
